### ISSUE TITLE
About New DataSource By Hive

### ISSUE THREAD

**Issue by BookXHD** [metatron-app/metatron-discovery#1914]
I've configed hdfs and hive configuration, and i can create datatset by hive, but when i create a datasource by hive, there appears an error in the "complete" step,and here is the error message: 
Caused by: java.lang.IllegalStateException: No segments found.. {"invalidRowCount":0,"indexedRows":0,"oobRows":0,"errRows":0,"flushedIndex":0} 
at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:344) ~[druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]

**Comment by kyungtaak** [comment]
@BookXHD can I get pull ingestion log? you can find logs through overlord console as below.
![image](https://user-images.githubusercontent.com/822255/56545555-ea3d9800-65b2-11e9-8c5b-ddf42c617e96.png)

**Comment by BookXHD** [comment]
Of course @kyungtaak 
[log.txt](https://github.com/metatron-app/metatron-discovery/files/3105520/log.txt)

**Comment by kyungtaak** [comment]
@BookXHD Hmm.. I'm sorry, but I think I need more information. Can I get the results of the command below and some sample data files?
```
describe formatted assist.account_status
```

**Comment by BookXHD** [comment]
yeah here is , but i am not sure if this is what you want @kyungtaak 

[sample.zip](https://github.com/metatron-app/metatron-discovery/files/3110384/sample.zip)

**Comment by kyungtaak** [comment]
@BookXHD Thank you for your information.
The reason I asked for additional table information was that I wanted to check if there were any unusualities in the tables you tested.

The cause is confirmed now. (There was a typo in the ingestion spec. :( )
This will be fixed soon, and I'll let you know when it's fixed.

**Comment by kyungtaak** [comment]
@BookXHD We fixed the issue you reported (#https://github.com/metatron-app/metatron-discovery/pull/1995) Would you try again in the new version(3.2.2) ?

**Comment by BookXHD** [comment]
@kyungtaak sorry , got really busy these days.I've tried again in the 3.2.2 version, and i found something else. I have table A in my own Hive data warehouse, and when i use the DB type in datasource to extract the data of table A, it works well but it still appears error when i use the Hive type in datasource to extract the same table.And this time, i tried another table which has less columns and has better quality data, then the Hive type works too, so i realized that the error before might be caused by the format of column or the quality of the data, but i think the error message do not give the specific description.
